## Explainable k-Medoids

In [ ]:
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn import metrics
import numpy as np
import pandas as pd

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)

In [ ]:
kmeans.inertia_

78.85144142614601

In [ ]:
metrics.accuracy_score(y,preds)

0.24

In [ ]:
centers = kmeans.cluster_centers_
print(centers)
print(centers.shape)

[[5.9016129  2.7483871  4.39354839 1.43387097]
 [5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]]
(3, 4)

In [ ]:
# one set of clusters for every obs - Idk. how to broadcast this to work with the later distance function
centers_lst = []

for i in preds:
    centers_lst.append(np.array(centers))
    
c = np.array(centers_lst)

In [ ]:
c = np.array(centers_lst)

In [ ]:
#Check obs
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
#check cluster
c[0]

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [ ]:
#check point-wise Manhatten distance
abs(c[0] - X[0])

array([[0.8016129 , 0.7516129 , 2.99354839, 1.23387097],
       [0.094     , 0.072     , 0.062     , 0.046     ],
       [1.75      , 0.42631579, 4.34210526, 1.87105263]])

In [ ]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
c

array([[[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       ...,

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]],

       [[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
        [5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85      , 3.07368421, 5.74210526, 2.07105263]]])

In [ ]:
#check point-wise euclidean distance
(c[0] - X[0])**2

array([[6.42583247e-01, 5.64921956e-01, 8.96133195e+00, 1.52243757e+00],
       [8.83600000e-03, 5.18400000e-03, 3.84400000e-03, 2.11600000e-03],
       [3.06250000e+00, 1.81745152e-01, 1.88538781e+01, 3.50083795e+00]])

In [ ]:
# to run with code above, I hashed the center_lst part
def calc_feature_wise_distance_matrix(distance_metric, points, cluster_centers):
    
    #centers_lst = []

    #for i in points:
    #    centers_lst.append(np.array(centers))
    
    c = np.array(centers_lst)

    # calculate the distance of every feature value of ever obs to every feature value in every cluster.
    
    feature_wise_distance_matrix = []
    
    if distance_metric == "manhattan":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append(abs(c[i] - e))
        
    
    if distance_metric == "euclidean":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append((c[i] - e)**2)
    
    return np.array(feature_wise_distance_matrix)

In [ ]:
A =calc_feature_wise_distance_matrix("manhattan", X, c)

In [ ]:
# Falsch!
def best_second_calc(feature_based_distances, preds):
    
    num_features = feature_based_distances.shape[2]
    
    assinged_cluster_list = []
    fb_distance_to_assinged_cluster_list = []
    
    best_alterantive_list = []
    fb_distance_to_best_alternative_list = []
    
    #for every obs:
    for idx, e in enumerate(feature_based_distances):
        #index of assinged cluster
        assigned_cluster = preds[idx]
        #feature-wise distances of point to assigned cluster
        distances_to_assigned = e[assigned_cluster]
        
        assinged_cluster_list.append(assigned_cluster)
        fb_distance_to_assinged_cluster_list.append(distances_to_assigned)
        
        #find best alternative:
        
        temp_bad = []
        temp_idx = []
        
        #for every feature
        for i in range(num_features):
            
            
            # best alternative: 
            best_alternative_distance = min(e[:,i])
            x = e[:,i].tolist()
            idx_best_alternative = x.index(best_alternative_distance)
            
            
            #if the best alternative is the assigned cluster, we have to find the second best alternative
            if idx_best_alternative == assigned_cluster:
                
                del x[idx_best_alternative]
                best_alternative_distance = min(x)
                idx_best_alternative = x.index(best_alternative_distance)
                
            temp_bad.append(best_alternative_distance)
            temp_idx.append(idx_best_alternative)

        best_alterantive_list.append(temp_idx)
        fb_distance_to_best_alternative_list.append(temp_bad)     
            
    return np.array(assinged_cluster_list), np.array(fb_distance_to_assinged_cluster_list), np.array(best_alterantive_list), np.array(fb_distance_to_best_alternative_list)

In [ ]:
ac ,fb_ac ,ba, fb_ba = best_second_calc(A, preds)

## Relevance of feature j for point i:

$$R_{ji} := R_j(x_{ij},c_{kj},c_{k'_{ij}}) := \frac{d_j(x_{ij},c_{k'_{ij}}) - d_j(x_{ij},c_{kj})}{d_j(x_{ij},c_{k'_{ij}}) + d_j(x_{ij},c_{kj})}$$

$d_j(x_{ij},c_{k'_{ij}}$ is the distance to the best alternative.

$d_j(x_{ij},c_{kj})$ is the distance to the associated cluster.

In [ ]:
fb_ba[0]

array([0.8016129 , 0.42631579, 2.99354839, 1.23387097])

In [ ]:
fb_ac[0]

array([0.094, 0.072, 0.062, 0.046])

In [ ]:
ac[0]

1

In [ ]:
ba[0]

array([0, 1, 0, 0])

In [ ]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [ ]:
preds[0]

1

In [ ]:
y[0]

0

In [ ]:
# broadcasted: for every i, for every j
R = (fb_ba - fb_ac) / (fb_ba + fb_ac)

In [ ]:
R

array([[ 0.79008788,  0.71102662,  0.95941809,  0.92811775],
       [ 0.80859739, -0.70625262,  0.95941809,  0.92811775],
       [ 0.59406025, -0.28698752,  0.9004776 ,  0.92811775],
       [ 0.52448239, -0.85145573,  0.97407513,  0.92811775],
       [ 0.9867785 ,  0.50738619,  0.95941809,  0.92811775],
       [ 0.1201556 ,  0.27290417,  0.83762847,  0.74071258],
       [ 0.52448239,  0.8419489 ,  0.95941809,  0.90908103],
       [ 0.9867785 ,  0.8419489 ,  0.97407513,  0.92811775],
       [ 0.42494184, -0.55382571,  0.95941809,  0.92811775],
       [ 0.80859739, -0.85145573,  0.97407513,  0.8026855 ],
       [ 0.1201556 ,  0.39442231,  0.97407513,  0.92811775],
       [ 0.68492204,  0.8419489 ,  0.9058518 ,  0.92811775],
       [ 0.68492204, -0.70625262,  0.95941809,  0.8026855 ],
       [ 0.38811228, -0.70625262,  0.8019449 ,  0.8026855 ],
       [-0.77308745,  0.23647604,  0.84835981,  0.92811775],
       [-0.54977669,  0.15416323,  0.97407513,  0.74071258],
       [ 0.1201556 ,  0.27290417,  0.9004776 ,  0.74071258],
       [ 0.79008788,  0.71102662,  0.95941809,  0.90908103],
       [-0.54977669,  0.32259919,  0.83762847,  0.90908103],
       [ 0.79008788,  0.32259919,  0.97407513,  0.90908103],
       [ 0.1201556 ,  0.8419489 ,  0.83762847,  0.92811775],
       [ 0.79008788,  0.39442231,  0.97407513,  0.74071258],
       [ 0.52448239,  0.50738619,  0.76034538,  0.92811775],
       [ 0.79008788,  0.27748069,  0.83762847,  0.57234412],
       [ 0.68492204,  0.8419489 ,  0.7011818 ,  0.92811775],
       [ 0.9867785 , -0.70625262,  0.9058518 ,  0.92811775],
       [ 0.9867785 ,  0.8419489 ,  0.9058518 ,  0.74071258],
       [ 0.56677712,  0.71102662,  0.97407513,  0.92811775],
       [ 0.56677712,  0.8419489 ,  0.95941809,  0.92811775],
       [ 0.59406025, -0.28698752,  0.9058518 ,  0.92811775],
       [ 0.68492204, -0.85145573,  0.9058518 ,  0.92811775],
       [ 0.1201556 ,  0.8419489 ,  0.97407513,  0.74071258],
       [ 0.56677712,  0.20862774,  0.97407513,  0.8026855 ],
       [-0.10315516,  0.18664744,  0.95941809,  0.92811775],
       [ 0.80859739, -0.85145573,  0.97407513,  0.92811775],
       [ 0.9867785 , -0.28698752,  0.84835981,  0.92811775],
       [-0.10315516,  0.71102662,  0.9004776 ,  0.92811775],
       [ 0.80859739,  0.50738619,  0.95941809,  0.8026855 ],
       [ 0.42494184, -0.70625262,  0.9004776 ,  0.92811775],
       [ 0.79008788,  0.8419489 ,  0.97407513,  0.92811775],
       [ 0.9867785 ,  0.71102662,  0.9004776 ,  0.90908103],
       [ 0.46949405, -0.43112057,  0.9004776 ,  0.90908103],
       [ 0.42494184, -0.28698752,  0.9004776 ,  0.92811775],
       [ 0.9867785 ,  0.71102662,  0.9058518 ,  0.40397567],
       [ 0.79008788,  0.32259919,  0.7011818 ,  0.74071258],
       [ 0.68492204, -0.70625262,  0.95941809,  0.90908103],
       [ 0.79008788,  0.32259919,  0.9058518 ,  0.92811775],
       [ 0.52448239, -0.28698752,  0.95941809,  0.92811775],
       [ 0.34346636,  0.39442231,  0.97407513,  0.92811775],
       [ 0.9867785 ,  0.27748069,  0.95941809,  0.92811775],
       [-0.75968992, -0.56286722,  0.54551177,  0.90390173],
       [-0.05102041, -0.56286722,  0.84212514,  0.79243272],
       [ 0.90461538,  0.85145573, -0.2488984 , -0.79243272],
       [ 0.10315516,  0.26618505,  0.63144924,  0.70412758],
       [-0.26190476,  0.68267223,  0.69381846,  0.79243272],
       [ 0.54977669,  0.68267223,  0.84212514,  0.70412758],
       [ 0.15986395, -0.62331498,  0.54551177,  0.47855049],
       [-0.80859739,  0.31827243,  0.25394485,  0.26949815],
       [-0.47278912,  0.06784969,  0.69381846,  0.70412758],
       [-0.56677712,  0.77071601,  0.57737879,  0.90390173],
       [-0.9867785 ,  0.17853149,  0.39039151,  0.26949815],
       [ 0.99639821, -0.54697286,  0.77697349,  0.79243272],
       [ 0.79251701,  0.22874881,  0.63144924,  0.26949815],
       [ 0.58163265,  0.06784969,  0.54551177,  0.90390173],
       [ 0.32646593,  0.06784969,  0.45861485,  0.70412758],
       [-0.68367347, -0.86073675,  0.99043183,  0.90390173],
       [ 0.32646593, -0.54697286,  0.84212514,  0.79243272],
       [ 0.77308745,  0.77071601,  0.69669327,  0.26949815],
       [ 0.3707483 ,  0.22874881,  0.84212514,  0.79243272],
       [ 0.32646593,  0.39570425,  0.57737879,  0.43786661],
       [ 0.99639821, -0.56286722,  0.39720509, -0.14921396],
       [ 0.58163265,  0.68267223,  0.63144924,  0.70412758],
       [ 0.15986395,  0.39570425,  0.2488984 ,  0.79243272],
       [ 0.58163265,  0.68267223,  0.54551177,  0.57667486],
       [-0.05102041,  0.06784969,  0.87816473,  0.70412758],
       [-0.47278912, -0.54697286,  0.99043183,  0.90390173],
       [-0.89455782,  0.68267223,  0.39720509,  0.90390173],
       [ 0.68367347,  0.54697286, -0.10059172, -0.16466827],
       [ 0.79251701,  0.06784969,  0.84212514,  0.79243272],
       [ 0.54977669,  0.52292576,  0.39039151,  0.26949815],
       [ 0.10315516,  0.31827243,  0.53183796,  0.43786661],
       [ 0.10315516,  0.31827243,  0.492956  ,  0.26949815],
       [ 0.77308745,  0.77071601,  0.57737879,  0.57667486],
       [ 0.79251701,  0.77071601, -0.04771497,  0.47855049],
       [-0.1201556 , -0.54697286,  0.84212514,  0.79243272],
       [ 0.79251701, -0.91760015,  0.84212514,  0.47855049],
       [-0.68367347, -0.86073675,  0.54551177,  0.79243272],
       [ 0.15986395,  0.26618505,  0.99043183,  0.70412758],
       [ 0.32646593, -0.54697286,  0.69669327,  0.70412758],
       [ 0.10315516,  0.39570425,  0.63144924,  0.70412758],
       [ 0.10315516,  0.52292576,  0.99043183,  0.57667486],
       [ 0.58163265, -0.54697286,  0.69381846,  0.90390173],
       [ 0.77308745,  0.52292576,  0.63144924,  0.57667486],
       [-0.9867785 ,  0.26618505,  0.25394485,  0.26949815],
       [ 0.32646593,  0.77071601,  0.77697349,  0.70412758],
       [ 0.54977669, -0.54697286,  0.77697349,  0.57667486],
       [ 0.54977669,  0.06784969,  0.77697349,  0.70412758],
       [ 0.3707483 ,  0.06784969,  0.87816473,  0.70412758],
       [-0.79008788,  0.39570425,  0.04927485,  0.43786661],
       [ 0.54977669,  0.68267223,  0.69669327,  0.70412758],
       [-0.15986395, -0.27748069,  0.72334032,  0.42618669],
       [ 0.77308745,  0.77071601, -0.04771497, -0.46309619],
       [ 0.65478842,  0.54697286,  0.81026216,  0.91670738],
       [-0.15986395, -0.06784969,  0.78924839,  0.14921396],
       [ 0.26190476,  0.54697286,  0.92092754,  0.71187405],
       [ 0.38735178,  0.54697286,  0.44007978,  0.91670738],
       [-0.80859739,  0.39570425,  0.84212514,  0.16466827],
       [ 0.51308901, -0.06784969,  0.54722701,  0.14921396],
       [ 0.68367347, -0.39570425,  0.92092754,  0.14921396],
       [ 0.57534247, -0.50738619,  0.65326096,  0.42618669],
       [ 0.26190476,  0.28698752,  0.04771497,  0.77697842],
       [ 0.05102041, -0.77071601,  0.34432834,  0.46309619],
       [ 0.89455782,  0.54697286,  0.64094171,  0.91670738],
       [ 0.54977669,  0.39570425,  0.10059172, -0.77697842],
       [ 0.77308745,  0.68267223, -0.04771497, -0.49200315],
       [ 0.05102041,  0.28698752,  0.34432834,  0.58186047],
       [ 0.26190476,  0.54697286,  0.64094171,  0.14921396],
       [ 0.35809988, -0.32259919,  0.41311697,  0.71187405],
       [ 0.35809988, -0.52292576,  0.36802113,  0.58186047],
       [ 0.79251701,  0.22874881,  0.10059172,  0.79243272],
       [ 0.90461538,  0.28698752,  0.93755508,  0.58186047],
       [ 0.32646593,  0.68267223,  0.2488984 , -0.77697842],
       [ 0.35809988, -0.68267223,  0.41311697,  0.77697842],
       [ 0.15986395,  0.77071601,  0.2488984 , -0.14921396],
       [ 0.68367347, -0.27748069,  0.93755508,  0.91670738],
       [ 0.57534247,  0.28698752,  0.72334032,  0.14921396],
       [ 0.3707483 ,  0.68267223,  0.39720509, -0.14921396],
       [ 0.58163265, -0.54697286,  0.2488984 , -0.14921396],
       [ 0.05102041, -0.68267223,  0.78924839,  0.91670738],
       [ 0.57534247,  0.54697286,  0.92092754, -0.47855049],
       [ 0.46299213, -0.68267223,  0.65326096,  0.46309619],
       [ 0.31111111, -0.32259919,  0.50614924,  0.77697842],
       [ 0.05102041, -0.68267223,  0.78924839,  0.71187405],
       [ 0.15986395,  0.68267223, -0.04771497,  0.79243272],
       [-0.58163265, -0.52292576,  0.78924839, -0.90390173],
       [ 0.35809988,  0.54697286,  0.65326096,  0.58186047],
       [-0.15986395, -0.8419489 ,  0.78924839,  0.49200315],
       [ 0.05102041,  0.85145573,  0.64094171,  0.14921396],
       [ 0.79251701, -0.54697286,  0.39720509, -0.14921396],
       [ 0.90461538,  0.85145573,  0.49263502,  0.91670738],
       [ 0.68367347,  0.85145573,  0.78924839,  0.49200315],
       [ 0.90461538,  0.85145573,  0.04771497,  0.58186047],
       [ 0.77308745,  0.77071601, -0.04771497, -0.46309619],
       [ 0.89455782,  0.28698752,  0.81026216,  0.58186047],
       [ 0.68367347, -0.27748069,  0.93755508,  0.42618669],
       [ 0.68367347,  0.54697286,  0.19602165,  0.58186047],
       [ 0.15986395,  0.39570425,  0.10059172, -0.46309619],
       [ 0.26190476,  0.54697286,  0.19602165,  0.77697842],
       [-0.3707483 , -0.8419489 ,  0.49263502,  0.58186047],
       [ 0.99639821, -0.54697286, -0.04771497, -0.14921396]])

In [ ]:
np.sum(R[:,0]) / len(R)

0.36975277918798033

In [ ]:
np.sum(R[:,1]) / len(R)

0.13387253867696042

In [ ]:
np.sum(R[:,2]) / len(R)

0.6688310755220815

In [ ]:
np.sum(R[:,3]) / len(R)

0.5876523318789212

## Cluster - wise relevances

In [ ]:
df_c = pd.DataFrame(R)
df_c.rename({0:"R1", 1: "R2", 2: "R3", 3: "R4"}, axis=1, inplace = True)
df_c["assigned_clusters"] = preds

In [ ]:
R_c = df_c.groupby(["assigned_clusters"]).mean()

In [ ]:
R_c

                         R1        R2        R3        R4
assigned_clusters
0                  0.221561  0.161347  0.528592  0.444371
1                  0.537161  0.153260  0.915832  0.869074
2                  0.391266  0.063536  0.572641  0.451136

## Example Random Noise

In [ ]:
def calc_feature_wise_distance_matrix(distance_metric, points, cluster_centers):
    
    centers_lst = []

    for i in points:
        centers_lst.append(np.array(centers))
    
    c = np.array(centers_lst)

    # calculate the distance of every feature value of ever obs to every feature value in every cluster.
    
    feature_wise_distance_matrix = []
    
    if distance_metric == "manhattan":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append(abs(c[i] - e))
        
    
    if distance_metric == "euclidean":
        for i,e in enumerate(X):
            feature_wise_distance_matrix.append((c[i] - e)**2)
    
    return np.array(feature_wise_distance_matrix)

In [ ]:
df_X = pd.DataFrame(X)
df_X.rename({0:"X1", 1: "X2", 2: "X3", 3: "X4"}, axis=1, inplace = True)

In [ ]:
X_5 = np.random.rand(150)
X_6 = np.random.rand(150)

In [ ]:
df_X["X_5"] = X_5
df_X["X6"] = X_6

In [ ]:
X = df_X.values
kmeans = KMeans(n_clusters=3, random_state=3).fit(X)

In [ ]:
df_X

      X1   X2   X3   X4       X_5        X6
0    5.1  3.5  1.4  0.2  0.581701  0.078518
1    4.9  3.0  1.4  0.2  0.333135  0.669149
2    4.7  3.2  1.3  0.2  0.344708  0.100558
3    4.6  3.1  1.5  0.2  0.832468  0.497231
4    5.0  3.6  1.4  0.2  0.459505  0.397849
..   ...  ...  ...  ...       ...       ...
145  6.7  3.0  5.2  2.3  0.274092  0.081572
146  6.3  2.5  5.0  1.9  0.224035  0.065515
147  6.5  3.0  5.2  2.0  0.847677  0.280314
148  6.2  3.4  5.4  2.3  0.423939  0.515724
149  5.9  3.0  5.1  1.8  0.124280  0.890807

[150 rows x 6 columns]

In [ ]:
kmeans.inertia_

105.5308837982973

In [ ]:
### !! darf ich nicht so machen, da sonst fehler bei cluster zuordnung!

#prediction is "false" but only because the "label" is not correct, the class itself is correctly predicted. Maybe this needs to be solved later on differently.
preds = kmeans.predict(X)

In [ ]:
centers

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [ ]:
centers = kmeans.cluster_centers_
print(centers)
print(centers.shape)

[[6.85384615 3.07692308 5.71538462 2.05384615 0.46545031 0.556783  ]
 [5.006      3.428      1.462      0.246      0.50337843 0.49798737]
 [5.88360656 2.74098361 4.38852459 1.43442623 0.51334673 0.51626077]]
(3, 6)

In [ ]:
A = calc_feature_wise_distance_matrix(distance_metric = "euclidean", points = X, cluster_centers=centers)

In [ ]:
ac ,fb_ac ,ba, fb_ba = best_second_calc(A, preds)

In [ ]:
# broadcasted: for every i, for every j
R = (fb_ba - fb_ac) / (fb_ba + fb_ac)

In [ ]:
for i in range(6):
    print("R " + str(i), np.sum(R[:,i]) / len(R))

R 0 0.5146801555673295
R 1 0.20692686957001968
R 2 0.8028122539080923
R 3 0.7069228372678296
R 4 -0.11776069385280437
R 5 -0.08682273747061511

Note, that the relevances $R_4$ and $R_5$ of $X_4$ and $X_5$ are close to zero, and even negative. According to the relevance coefficients, $X_4$ and $X_5$ are therefore irrelevant, even a bit harmful for the clustering process overall. As each additional feature increases the $SSW$, $X_4$ and $X_5$ should be excluded from the clustering process.